name: Удалять results.json через 2 минуты после пуша

permissions:
  contents: write

on:
  push:
    paths:
      - results.json

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Забрать код
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Настроить Git-пользователя
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ждать 2 минуты
        run: sleep 160

      - name: Удалить results.json и закоммитить
        run: |
          git rm results.json
          git commit -m "Авто: удаляю results.json спустя 4 минуты" || echo "Nothing to commit"
          git push || echo "Push failed"
